config/routes.rb
Rails.application.routes.draw do

  root 'homepage#index'

    get 'login' => 'sessions#new'
    post 'login' => 'sessions#create'
    get 'logout' => 'sessions#destroy'

    resources :artists
    resources :albums
    resources :users

    resources :songs do
      member do
        put 'render_section_form'
        put 'cancel_section_form'
        put 'create_section'
        put 'delete_section'
        put 'change_stress'
        put 'change_end_rhyme'
        put 'change_lyrics'
        put 'change_rhythm'
        put 'change_rhyme'
        put 'add_cell'
        put 'delete_cell'
        put 'add_measure_after'
        put 'add_measure_before'
        put 'delete_measure'
        put 'publish'
        put 'open_edit_menu'
        put 'close_edit_menu'
        put 'tag_for_publication'
        put 'render_delete_song_warning'
        put 'render_delete_section_warning'
      end
    end

end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
    @songs = Song.all
  end
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/homepage/index.erb
<div class="row">
  <div class="small-12 large-10 columns large-centered">
    <h1 class="text-center logo small-padding">Rapp</h1>

    <ul class="tabs" data-tabs id="songs-tabs">
      <li class="tabs-title is-active"><a href="#published-songs" aria-selected="true">Published Transcriptions</a></li>
      <% if current_user %>
        <li class="tabs-title"><a href="#personal-songs">Your Transcriptions</a></li>
      <% end %>
    </ul>
    <div class="tabs-content" data-tabs-content="songs-tabs">
      <div class="tabs-panel is-active" id="published-songs">
        <table>
          <thead>
            <tr>
              <th width="400">Song</th>
              <th>Artists</th>
              <th width="300">Album</th>
            </tr>
          </thead>
          <tbody>
            <% Song.where(published: true).each do |song| %>
              <tr>
                <td><a href="/songs/<%= song.id %>"><%= song.name %></a></td>
                <td><%= song.comma_separated_artists %></td>
                <td><%= song.album.title %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      <% if current_user %>
        <div class="tabs-panel" id="personal-songs">
          <table>
            <thead>
              <tr>
                <th width="400">Song</th>
                <th>Artists</th>
                <th width="300">Album</th>
              </tr>
            </thead>
            <tbody>
              <% Song.where(transcriber_id: current_user.id).each do |song| %>
                <tr>
                  <td><a href="/songs/<%= song.id %>"><%= song.name %></a></td>
                  <td><%= song.comma_separated_artists %></td>
                  <td><%= song.album.title %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      <% end %>
    </div>

    <!-- Add Path to edit songs -->
    <!-- make more conditional -->
    <!-- Also change size of tabs if possible -->

    <!-- refactor add space without using row with empty p tags -->
    <div class="row">
      <p></p>
    </div>
    <div class="row">
      <div class="small-2 columns small-centered">
        <a class="large button text-centered" href="<%= new_song_path %>">New Song</a>
      </div>
    </div>
  </div>
</div>