config/routes.rb
Rails.application.routes.draw do

  root 'homepage#index'

    get 'login' => 'sessions#new'
    post 'login' => 'sessions#create'
    get 'logout' => 'sessions#destroy'

    resources :artists
    resources :albums
    resources :users

    resources :songs do
      member do
        put 'render_section_form'
        put 'cancel_section_form'
        put 'create_section'
        put 'delete_section'
        put 'change_stress'
        put 'change_end_rhyme'
        put 'change_lyrics'
        put 'change_rhythm'
        put 'change_rhyme'
        put 'add_cell'
        put 'delete_cell'
        put 'add_measure_after'
        put 'add_measure_before'
        put 'delete_measure'
        put 'publish'
        put 'open_edit_menu'
        put 'close_edit_menu'
        put 'tag_for_publication'
        put 'render_delete_song_warning'
        put 'render_delete_section_warning'
      end
    end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />


    <title><%= content_for?(:title) ? yield(:title) : "Rapp" %></title>

    <%= stylesheet_link_tag    "application" %>
    <link href='https://fonts.googleapis.com/css?family=Oleo+Script' rel='stylesheet' type='text/css'>
    <% javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="top-bar">
      <div class="top-bar-left">
        <ul class="menu">
          <li><a class="logo" href="/">Rapp</a></li>
          <li><a href="https://github.com/markjanzer/rap-analysis"><i class="fa fa-github red" aria-hidden="true"></i></a></li>
        </ul>
      </div>
      <div class="top-bar-right">
        <ul class="menu">
        <% if current_user.nil? %>
          <li><%= link_to "Login", login_path %></li>
          <li><%= link_to "Create Account", new_user_path %></li>
        <% else %>
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Logout", logout_path, method: :delete %></li>
        <% end %>
        </ul>
      </div>
    </div>
    <%= yield %>

  </body>
</html>